version: "3.9"
services:
  frontend:
    depends_on: 
    - backend 
    build: .
    ports:
     - "3000:3000"
    environment:
     - REACT_APP_BACKEND_URL=http://localhost:3001/api/helsinkiservices?query=
  backend:
    depends_on:
    - redis
    build: https://github.com/jacker92/servicelocator-backend.git
    ports:
      - "3001:80"
    environment:
    - REDIS_ENDPOINT=redis:6379
    networks:
      - app-tier
  redis:
    image: "bitnami/redis:latest"
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge