version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master